### ISSUE TITLE
Logbook settings not permanent

### ISSUE THREAD

**Issue by leonardinux** [k0swe/forester#2298]
logbook settings data not saved.

**Comment by xylo04** [comment]
I can reproduce what you're seeing: changes to the QTH station in the logbook settings does not update after a save. Definitely a bug.

As a workaround, try this: save, and the reload the page and check again. From what I can see, the information is actually being saved, but the local snapshot of the info are not updated. Therefore the saved info does not take effect until page reload.

I'll have a fix for this shortly. Thanks for the report!
