### ISSUE TITLE
Blue-on-black text is hard to read

### ISSUE THREAD

**Issue by flwyd** [k0swe/forester#981]
When editing a QSO, the changed fields change from white text on a dark gray background to dark blue text on a dark gray background.  The latter is really hard to read, and since it happens as soon as a single character is changed, it's hard to verify that you're tying the correct value.

**Comment by xylo04** [comment]
Agreed. I was playing around with Angular Material dark theme, but it needs more work. aab15cbd66201785b6fce33822da1f4bb50636ad

Ideally I'd like to make the theme switchable between light and dark.
