### ISSUE TITLE
Chrome Auto-fill Gets in the Way of Contact Country Popup

### ISSUE THREAD

**Issue by flwyd** [k0swe/forester#982]
Chrome seems eager to auto-fill my own address into the City, State, and Country fields in the "Contacted Station".  I can mostly ignore the city and state popups, but the one for country is kind of annoying, since the Chrome auto-fill popup is above Forester's own autocomplete list of countries.

Apparently it's difficult to tell Chrome not to auto-fill a field that looks like an address, but there are [some hacks people have tried](https://gist.github.com/eduardo-mior/ad14cab17fb5ab641812bff622534353).  Accepting "USA" for "United States" might make this a little less annoying.

**Comment by xylo04** [comment]
I usually have Chrome autofill disabled, but yeah, I see what you mean:

![image](https://user-images.githubusercontent.com/389971/159732321-a65ea6f0-4e50-449c-8672-7b0886502306.png)

**Comment by xylo04** [comment]
Made an attempt in dce083d42d730aa531a6b0fd100438067f64742f, only for the contacted station right now. See if that helps.

**Comment by xylo04** [comment]
Setting `autocomplete` to an invalid value (I used `dummy`) seems to do the job, at least in Chrome.

**Comment by flwyd** [comment]
Yeah, this looks like it's working on Chrome.

**Comment by xylo04** [comment]
This trick does not appear to help in Safari, but it's a little less irritating there because Autofill does not kick in unless it matches a contact.
