### ISSUE TITLE
Autocapitalize Callsigns

### ISSUE THREAD

**Issue by flwyd** [k0swe/forester#983]
When typing one-handed or on a phone, it's challenging to capitalize all letters in a callsign.  It looks like [`autocapitalize="characters"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize) can do this automatically.

**Comment by xylo04** [comment]
Great suggestion! Added in 1669bf7a501360703d627d0414471108a2041a1e. From the doc it sounds like `autocapitalize` is mainly for mobile virtual keyboards, not physical keyboards, so there may be more work required.

Also, this reminds me about #9: QSO entry on mobile needs a lot of love!

**Comment by flwyd** [comment]
> From the doc it sounds like autocapitalize is mainly for mobile virtual keyboards, not physical keyboards.

Yeah, it looks like this effectively triggers the shift key on the on-screen mobile keyboard after each character.  It doesn't seem to have an effect on non-mobile Chrome, and if you hit shift (to go to lower case) on mobile and type a letter it stays lower case in the input field.  That said, I think this is a big improvement on mobile, and hitting shift on a laptop isn't too bad.

**Comment by xylo04** [comment]
I didn't mean to close this, there's more we can do here relatively easy. There's no use case I can think of for ever allowing lower case in a callsign.
